config/routes.rb
Rails.application.routes.draw do
  resources :inventories do
    collection do
      post 'check_quantity_exceeded' => 'inventories#check_quantity_exceeded'
    end
  end
  root "home#index"
  resources :accessories
  resources :guitars
  resources :brands
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  post '/add_to_cart'=> 'home#add_to_cart'
  post '/remove_from_cart'=> 'home#remove_from_cart'
  get '/show'=> 'home#show'
  get '/cart'=> 'home#cart'
  # get '/home'=> 'home#index'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/inventory.rb
class Inventory < ApplicationRecord
    belongs_to :guitar, optional: :true
    belongs_to :accessory, optional: :true

    after_save :update_remaining_count_and_price

    def product
        self.is_accessory ? self.accessory : self.guitar
    end

    def update_remaining_count_and_price
       
        product = self.product
        current_quantity = product.remaining_quantity
        updated_quantity = (self.stock_status == "in") ? (current_quantity.to_i + self.quantity.to_i) : (current_quantity.to_i - self.quantity.to_i)
        updated_price = (self.stock_status == "in") ? (self.price_per_unit.to_f) : product.price.to_f
        product.update(remaining_quantity: updated_quantity, price: updated_price)
    end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token , only: [:check_quantity_exceeded]
  before_action :redirect_to_root_if__not_admin

  # GET /inventories
  # GET /inventories.json
  def index
    respond_to do |format|
      format.html
      format.json{render json: InventoryDatatable.new(view_context)}
    end
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to inventories_url, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to inventories_url, notice: 'Inventory was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def check_quantity_exceeded
    message= ""
    if params[:is_accessory] == "true"
      product = Accessory.find_by_id(params[:product_id])
    else
      product = Guitar.find_by_id(params[:product_id])
    end
    message = "stock is not available for selected quantity. available stock is #{product.remaining_quantity.to_i}" if(product.remaining_quantity.to_i < params[:quantity].to_i)
    
    render :json => {message: message}, status: :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params.require(:inventory).permit(:is_accessory, :guitar_id, :accessory_id, :stock_status, :quantity, :price_per_unit, :total_price)
    end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<% action = (params[:action] == 'new' || params[:action] == 'create') ? 'new' : 'update'   %>
<div class="row">
  <div class="col-md-6 offset-md-3 col-sm-12 col-xs-12 margin-top-3">
      <div class="white-box">
          <h3 class="box-title m-b-0"><%= action%> Inventroy</h3>
            <div class="white-box">
              <div class="row">
                  <div class="col-sm-12 col-xs-12">
                      <%= form_with(model: inventory, local: true) do |f| %>
                          <div class="form-group">
                              <label for="is_accessory">Is Accessory</label>
                              <%= f.select :is_accessory, options_for_select([['Yes', true], ['No', false]], f.object.is_accessory), {}, {:class => 'form-control'}%> 
                          </div>
                          <div class="form-group guitar-select ">
                              <label for="guitar_id">Guitar</label>
                              <%= f.select :guitar_id, options_for_select(Guitar.all.map { |guitar| [guitar.name, guitar.id] }, f.object.guitar_id), {:prompt => 'Select Guitar'}, {:class => 'form-control'}%> 
                          </div>
                          <div class="form-group accessory-select hide">
                              <label for="accessory_id">Accessory</label>
                              <%= f.select :accessory_id, options_for_select(Accessory.all.map { |accessory| [accessory.name, accessory.id] }, f.object.accessory_id), {:prompt => 'Select Accessory'}, {:class => 'form-control'}%> 
                          </div>
                          <div class="form-group">
                              <label for="stock_status">Stock Status</label>
                              <%= f.select :stock_status, options_for_select([['In', 'in'], ['Out', 'out']], f.object.stock_status), {}, {:class => 'form-control'}%> 
                          </div>
                          <div class="form-group">
                              <label for="quantity">Quantity</label>
                              <%= f.number_field :quantity, :class=>"form-control", :placeholder=>"Quantity", :id=>"quantity"%>
                          </div>
                          <div class="form-group">
                              <label for="price_per_unit">Price Per Unit</label>
                              <%= f.number_field :price_per_unit, :class=>"form-control", :placeholder=>"Price Per Unit", :id=>"price_per_unit", :step=>'0.001'%>
                          </div>

                          <div class="form-group">
                              <label for="total_price">Total</label>
                              <%= f.number_field :total_price, :class=>"form-control", :placeholder=>"Total", :id=>"total_price", :step=>'0.001', :readonly=> true%>
                          </div>
          

                          <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Submit</button>

                          <%= link_to 'Cancel', guitars_path, :class => "btn btn-inverse waves-effect waves-light"%>
                          
                      <% end %>
                  </div>
              </div>
            </div>
          </div>
    </div>
</div>

<script>
$(function(){
  $('[name="inventory[is_accessory]"]').unbind('change').bind('change', function(){
    if($(this).val() === 'true'){
      $('[name="inventory[guitar_id]"]').val("").addClass('disabled')
      $('[name="inventory[accessory_id]"]').removeClass('disabled')
      $('.guitar-select').addClass('hide')
      $('.accessory-select').removeClass('hide')
    }else{
      $('[name="inventory[accessory_id]"]').val("").addClass('disabled')
      $('[name="inventory[guitar_id]"]').removeClass('disabled')
      $('.accessory-select').addClass('hide')
      $('.guitar-select').removeClass('hide')
    }

  });
  $('#quantity').unbind('focusout').bind('focusout', function(){
    if($('[name="inventory[stock_status]"]').val() === "out"){
      if($('[name="inventory[guitar_id]"]').val() === "" && $('[name="inventory[accessory_id]"]').val() === ""){
        alert('please select guitar / accessory');
        $(this).val(0);
      }else{
        checkQuantityExceed();
      }
    }
  })
  $('#quantity, #price_per_unit').unbind('keyup').bind('keyup', function(){
    calculateTotal()
  })
  function calculateTotal(){
    let quantity = parseInt($('#quantity').val()) || 0, ppu = parseFloat($("#price_per_unit").val()) || 0;
    let total = ppu * quantity;
    $("#total_price").val(total.toFixed(2))
  }
  function checkQuantityExceed(){
    let is_accessory= $('[name="inventory[is_accessory]"]').val()
    let data ={
      is_accessory: is_accessory,
      product_id: (is_accessory === "true") ? $('[name="inventory[accessory_id]"]').val() : $('[name="inventory[guitar_id]"]').val(),
      quantity: $('#quantity').val()
    }
    $.ajax({url: "<%=check_quantity_exceeded_inventories_path%>",
          data: JSON.stringify(data), 
          type: "POST",
          dataType: 'json',
          contentType : 'application/json',
          success: function(res){
          if(res.message.length > 0){
            alert(res.message);
            $('#quantity').val(0)
          }
              
      }});
  }
})
</script>

app/views/inventories/edit.html.erb
<%= render 'form', inventory: @inventory %>

app/views/inventories/index.html.erb
<p id="notice"><%= notice %></p>

<% url = '/'+params[:controller]+'.json' %>
<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Inventory</h4> </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12"> 
      <a href="<%=new_inventory_path%>" class="btn btn-danger pull-right m-l-20 btn-rounded btn-outline hidden-xs hidden-sm waves-effect waves-light add_new_btn">Add New</a>
    </div>
</div>

<div class="row">
  <div class="col-sm-12">
      <div class="white-box">
          <div class="table-responsive">
              <table id="sample-table-2" class="table table-striped" data-source="<%= url%>">
                  <thead>
                      <tr>
                          <th>Product Name</th>
                          <th>Is Accessory</th>
                          <th>Quantity</th>
                          <th>Price per unit</th>
                          <th>Total price</th>
                          <th>Updated At</th>
                          <th></th>
                      </tr>
                  </thead>
                  <tbody>
                  </tbody>
              </table>
          </div>
      </div>
  </div>
</div>

<script>
  $(function(){
    initDatatables(1, "ASC");
  })
</script>

app/views/inventories/new.html.erb
<%= render 'form', inventory: @inventory %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Is accessory:</strong>
  <%= @inventory.is_accessory %>
</p>

<p>
  <strong>Guitar:</strong>
  <%= @inventory.guitar_id %>
</p>

<p>
  <strong>Accessory:</strong>
  <%= @inventory.accessory_id %>
</p>

<p>
  <strong>Stock status:</strong>
  <%= @inventory.stock_status %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @inventory.quantity %>
</p>

<p>
  <strong>Price per unit:</strong>
  <%= @inventory.price_per_unit %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @inventory.total_price %>
</p>

<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>