config/routes.rb
Rails.application.routes.draw do
  resources :inventories do
    collection do
      post 'check_quantity_exceeded' => 'inventories#check_quantity_exceeded'
    end
  end
  root "home#index"
  resources :accessories
  resources :guitars
  resources :brands
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  post '/add_to_cart'=> 'home#add_to_cart'
  post '/remove_from_cart'=> 'home#remove_from_cart'
  get '/show'=> 'home#show'
  get '/cart'=> 'home#cart'
  # get '/home'=> 'home#index'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/guitar.rb
class Guitar < ApplicationRecord
    belongs_to :brand
    mount_uploader :image, GuitarUploader
    before_create :set_serial_number
    
    validates :name, presence: true
    validates :description, presence: true
    validates :brand_id, presence: true
    validates :guitar_type, presence: true
    validates :number_of_strings, presence: true
    validates :image, presence: true
    validates :name, uniqueness: { scope: :brand_id }

    def set_serial_number
        if self.guitar_type.present?
            pre = (self.guitar_type == "electric") ? "EC" : "AC"
            number = (rand() * 100000).to_i
            self.serial_number = pre + number.to_s
        end
    end
end

app/controllers/guitars_controller.rb
class GuitarsController < ApplicationController
  before_action :set_guitar, only: [:show, :edit, :update, :destroy]
  before_action :redirect_to_root_if__not_admin

  # GET /guitars
  # GET /guitars.json
  def index
    respond_to do |format|
      format.html
      format.json{render json: GuitarDatatable.new(view_context)}
    end
  end

  # GET /guitars/1
  # GET /guitars/1.json
  def show
  end

  # GET /guitars/new
  def new
    @guitar = Guitar.new
  end

  # GET /guitars/1/edit
  def edit
  end

  # POST /guitars
  # POST /guitars.json
  def create
    @guitar = Guitar.new(guitar_params)

    respond_to do |format|
      if @guitar.save
        format.html { redirect_to guitars_url, notice: 'Guitar was successfully created.' }
        format.json { render :show, status: :created, location: @guitar }
      else
        format.html { render :new }
        format.json { render json: @guitar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guitars/1
  # PATCH/PUT /guitars/1.json
  def update
    respond_to do |format|
      if @guitar.update(guitar_params)
        format.html { redirect_to guitars_url, notice: 'Guitar was successfully updated.' }
        format.json { render :show, status: :ok, location: @guitar }
      else
        format.html { render :edit }
        format.json { render json: @guitar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guitars/1
  # DELETE /guitars/1.json
  def destroy
    @guitar.destroy
    respond_to do |format|
      format.html { redirect_to guitars_url, notice: 'Guitar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guitar
      @guitar = Guitar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guitar_params
      params.require(:guitar).permit(:name, :description,:brand_id, :guitar_type, :number_of_strings, :serial_number, :remaining_quantity, :image)
    end
end

app/helpers/guitars_helper.rb
module GuitarsHelper
end

app/views/guitars/_form.html.erb
<% action = (params[:action] == 'new' || params[:action] == 'create') ? 'new' : 'update'   %>
<div class="row">
  <div class="col-md-6 offset-md-3 col-sm-12 col-xs-12 margin-top-3">
      <div class="white-box">
          <h3 class="box-title m-b-0"><%= action%> Guitar</h3>
            <div class="white-box">
              <div class="row">
                  <div class="col-sm-12 col-xs-12">
                      <%= form_with(model: guitar, local: true) do |f| %>
                            <% if guitar.errors.any? %>
                                <div id="error_explanation">
                                <h2><%= pluralize(guitar.errors.count, "error") %> prohibited this guitar from being saved:</h2>

                                <ul>
                                <% guitar.errors.full_messages.each do |message| %>
                                    <li><%= message %></li>
                                <% end %>
                                </ul>
                                </div>
                            <% end %>
                          <div class="form-group">
                              <label for="name">Name</label>
                              <%= f.text_field :name, :class=>"form-control", :placeholder=>"Name", :id=>"name"%>
                          </div>
                          <div class="form-group">
                              <label for="description">Description</label>
                              <%= f.text_area :description, :class=>"form-control", :placeholder=>"Description", :id=>"description"%>
                          </div>
                          <div class="form-group">
                              <label for="brand_id">brand</label>
                              <%= f.select :brand_id, options_for_select(Brand.all.map { |brand| [brand.name, brand.id] }, f.object.brand_id), {:prompt => 'Select Brand'}, {:class => 'form-control'}%> 
                          </div>
                          <div class="form-group">
                              <label for="guitar_type">Guitar Type</label>
                              <%= f.select :guitar_type, options_for_select($GUITAR_TYPES[0..1], f.object.guitar_type), {:prompt => 'Select Guitar Type'}, {:class => 'form-control'}%> 
                          </div>
                          <div class="form-group">
                            <label for="number_of_strings">Number of strings</label>
                            <%= f.number_field :number_of_strings, :class=>"form-control", :placeholder=>"Number Of Strings", id: :guitar_number_of_strings %>
                          </div>

                          <div class="form-group">
                            <label for="image">Image</label>
                            <%= f.file_field :image, id: :guitar_image, :class=>"form-control" %>
                          </div>
                          <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Submit</button>

                          <%= link_to 'Cancel', guitars_path, :class => "btn btn-inverse waves-effect waves-light"%>
                          
                      <% end %>
                  </div>
              </div>
            </div>
          </div>
    </div>
</div>

app/views/guitars/edit.html.erb
<%= render 'form', guitar: @guitar %>

app/views/guitars/index.html.erb
<p id="notice"><%= notice %></p>

<% url = '/'+params[:controller]+'.json' %>
<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Guitars</h4> </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12"> 
      <a href="<%=new_guitar_path%>" class="btn btn-danger pull-right m-l-20 btn-rounded btn-outline hidden-xs hidden-sm waves-effect waves-light add_new_btn">Add New</a>
    </div>
</div>

<div class="row">
  <div class="col-sm-12">
      <div class="white-box">
          <div class="table-responsive">
              <table id="sample-table-2" class="table table-striped" data-source="<%= url%>">
                  <thead>
                      <tr>
                          <th>Serial number</th>
                          <th>Name</th>
                          <th>Description</th>
                          <th>Brand</th>
                          <th>Guitar type</th>
                          <th>Number of strings</th>
                          <th>Image</th>
                          <th>Updated At</th>
                          <th></th>
                      </tr>
                  </thead>
                  <tbody>
                  </tbody>
              </table>
          </div>
      </div>
  </div>
</div>

<script>
  $(function(){
    initDatatables(1, "ASC");
  })
</script>

app/views/guitars/new.html.erb
<%= render 'form', guitar: @guitar %>