config/routes.rb
Rails.application.routes.draw do
  resources :inventories do
    collection do
      post 'check_quantity_exceeded' => 'inventories#check_quantity_exceeded'
    end
  end
  root "home#index"
  resources :accessories
  resources :guitars
  resources :brands
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  post '/add_to_cart'=> 'home#add_to_cart'
  post '/remove_from_cart'=> 'home#remove_from_cart'
  get '/show'=> 'home#show'
  get '/cart'=> 'home#cart'
  # get '/home'=> 'home#index'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_leftbar.html.erb
<!-- Left navbar-header -->
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse slimscrollsidebar">
        <% if user_signed_in?%>
            <div class="user-profile">
                <div class="dropdown user-pro-body">
                    <div><img src="/assets/users/default_user.png" alt="user-img" class="img-circle"></div>
                    
                </div>
            </div>
        <% end %>
        <ul class="nav" id="side-menu">
            <% if !user_signed_in?%>

            <% elsif current_user.is_admin  %>
                
                <li><a href="<%=  brands_url %>"><i class=" fa fa-home"></i> Brands</a></li>
                <li><a href="<%= guitars_url%>"><i class="ti-user"></i>Guitars</a></li>
                <li><a href="<%= accessories_url %>"><i class="fa  fa-cube"></i> Accessories</a></li>
                <li><a href="<%= inventories_url %>"><i class="fa fa-copy"></i> Inventories</a></li>
                <li><a href="<%= destroy_user_session_path %>" data-method="delete" class="waves-effect"><i class="icon-logout fa-fw"></i> <span class="hide-menu">Log out</span></a></li>
            <% else  %>
                
                <li >
                    <a href="#"><i class=" fa fa-home"></i> Guitars</a></li>
                    <ul>
                        <% $GUITAR_TYPES[0..1].each do |guitar_type| %>
                            <li>
                                <a href="<%= root_path({:p=> 'guitar', :t=> guitar_type[1]})%>"><%=guitar_type[0]%></a> 
                            </li>
                        <% end %>
                    </ul>
                </li>
                <li >
                    <a href="#"><i class=" fa fa-home"></i> Accessories</a></li>
                    <ul>
                        <% $GUITAR_TYPES.each do |guitar_type| %>
                            <li>
                                <a href="<%= root_path({:p=> 'accesory', :t=> guitar_type[1]})%>"><%=guitar_type[0]%></a> 
                            </li>
                        <% end %>
                    </ul>
                </li>
                <li><a href="<%= destroy_user_session_path %>" data-method="delete" class="waves-effect"><i class="icon-logout fa-fw"></i> <span class="hide-menu">Log out</span></a></li>

            <% end %>

        </ul>
    </div>
</div>
<!-- Left navbar-header end -->

app/views/shared/_topbar.html.erb
<nav class="navbar navbar-default navbar-static-top m-b-0">
    <div class="navbar-header"> <a class="navbar-toggle hidden-sm hidden-md hidden-lg " href="javascript:void(0)" data-toggle="collapse" data-target=".navbar-collapse"><i class="ti-menu"></i></a>
        <div class="top-left-part"><a class="logo" href="/"><b><!--This is dark logo icon--><img src="/assets/eliteadmin-logo.png" alt="home" class="dark-logo" /><!--This is light logo icon--><img src="/assets/eliteadmin-logo-dark.png" alt="home" class="light-logo" /></b><span class="hidden-xs"><!--This is dark logo text--><img src="/assets/eliteadmin-text.png" alt="home" class="dark-logo" /><!--This is light logo text--><img src="/assets/eliteadmin-text-dark.png" alt="home" class="light-logo" /></span></a></div>
        <ul class="nav navbar-top-links navbar-right pull-right ">
            
            <li class="nav-item right-side-toggle"> 
                <a class="nav-link  waves-effect waves-light" href="<%= cart_path %>">
                    <i class="fa fa-shopping-cart"></i> Cart
                    
                </a>
            </li>
            <% if user_signed_in?%>
                <li class="nav-item right-side-toggle"> 
                    <a class="nav-link  waves-effect waves-light" href="javascript:void(0)">
                        <i class="fa fa-user"></i> <%= current_user.email %>
                    </a>
                </li>
                <li class="nav-item right-side-toggle"> 
                    <a class="nav-link  waves-effect waves-light" href="<%= destroy_user_session_path %>" data-method="delete">
                        <i class="fa fa-sign-in"></i> 
                    </a>
                </li>
            <% else %>
                <li class="nav-item right-side-toggle"> 
                    <a class="nav-link  waves-effect waves-light" href="<%= new_user_session_path%>">
                        <i class="fa fa-user"></i> Login
                    </a>
                </li>
            <% end %>
                 
        </ul> 
    </div>
</nav>