config/routes.rb
Rails.application.routes.draw do
  resources :inventories do
    collection do
      post 'check_quantity_exceeded' => 'inventories#check_quantity_exceeded'
    end
  end
  root "home#index"
  resources :accessories
  resources :guitars
  resources :brands
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  post '/add_to_cart'=> 'home#add_to_cart'
  post '/remove_from_cart'=> 'home#remove_from_cart'
  get '/show'=> 'home#show'
  get '/cart'=> 'home#cart'
  # get '/home'=> 'home#index'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :set_product, :only=>[:add_to_cart, :show, :remove_from_cart]
    before_action :set_defaults , only: [:index]
    skip_before_action :verify_authenticity_token , only: [:add_to_cart, :remove_from_cart]
    skip_before_action :authenticate_user!

    def index
        if current_user.present? and current_user.is_admin
            return redirect_to(brands_url)
        end
        @brands= get_brands
        @no_of_strings = (params[:p] == "guitar") ? Guitar.pluck(:number_of_strings).uniq : []
        @products = get_records
    end

    def show
        @related_products = Guitar.all
    end

    def cart
    end

    def add_to_cart
        quantity = params[:qt].present? ? params[:qt].to_i : 1
        unless @product.remaining_quantity.to_i >= quantity
            return render :json=> {:message=> "insufficient inventory"}, :status=> 401
        end

        @shopping_cart.add(@product, @product.price, quantity)
        @product.update(remaining_quantity: (@product.remaining_quantity - quantity))
        render :json=> {:message=> "item added to cart"}, status: :ok
    end

    def remove_from_cart
        quantity = params[:qt].present? ? params[:qt].to_i : 1
        @shopping_cart.remove(@product, quantity)
        @product.update(remaining_quantity: (@product.remaining_quantity + quantity))
        render :json=> {:message=> "item removed from cart"}, status: :ok
    end

    private
        def get_records
            search_obj = {}
            query=""
            if params[:t] == "all"
                query = 'remaining_quantity > 0'
            else
                query = 'remaining_quantity > 0 and guitar_type = :type'
                search_obj[:type] = params[:t]
            end

            if params[:b].present?
                brands = params[:b].split(',')
                query = query + " and brands.name IN (:brands)"
                search_obj[:brands] = brands
            end

            if params[:n].present? and params[:p] == "guitar"
                strings = params[:n].split(',')
                query = query + " and guitars.number_of_strings IN (:stings)"
                search_obj[:stings] = strings
            end

            res = params[:p].classify.constantize.eager_load(:brand).where(query, search_obj).offset(params[:offset].to_i).limit(10)
            res
        end

        def get_brands
            if params[:p].present?
                res= params[:p].classify.constantize.where('remaining_quantity > 0').map{|x| x.brand.name}.uniq 
            end
            res
        end

        def set_product
            @product = params[:pc].classify.constantize.find_by_id(params[:pi])
        end

        def set_defaults
            first_rec = Guitar.where('remaining_quantity > 0').first
            if params[:p].nil?
                params[:p] =$PRODUCTS[0][1]
            end

            if params[:t].nil?
                params[:t] =$GUITAR_TYPES[0][1]
            end

            if params[:b].nil?
                params[:b] = first_rec.brand.name rescue ''
            end

            if params[:n].nil?
                params[:n] = first_rec.number_of_strings.to_s rescue ""
            end

            # binding.pry
        end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_card.html.erb
 <div style="padding: 5px" class="custom-card">
    <a href="<%= show_path({:pc=> product.class , :pi=> product.id })%>">
        <img class="img-responsive" alt="eCommerce Product List" src="<%= product.image_url%>" />
        <br />
        <h2 class="pull-right">₹ <%= product.price%></h2>
        <h2><a href="#"><%= product.name.truncate(12) %></a></h2>
        <h4><a class="text-muted"><%= product.brand.name.truncate(12) %></a></h4>
        <br />
        <p class="text-justify"><%= product.description.truncate(50, separator: ' ')%></p>
    </a>
    <br />
    <div class="btn-ground text-center" style="padding-bottom: 30px">
        <button type="button" class="btn btn-primary btn-block add-to-cart" data-product-class="<%=product.class%>" data-product-id="<%= product.id %>">
            <i class="fa fa-shopping-cart"></i> Add To Cart
        </button>
    </div>
</div>

app/views/home/cart.html.erb
 <div class="row bg-title">
    <div class="col-sm-12 text-center">
        <h4 class="page-title">Cart</h4> </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
  <div class="col-sm-8 offset-sm-2">
      <% if @shopping_cart.total_unique_items > 0 %>
         <div class="row white-box">
            <div class="col-12">
                  <div class="table-responsive">
                     <table class="table table-striped">
                        <thead>
                              <tr>
                                 <th scope="col" class="text-center"> Image</th>
                                 <th scope="col" class="text-center" >Product</th>
                                 <th scope="col" class="text-center">Quantity</th>
                                 <th scope="col" class="text-center">Price</th>
                                 <th scope="col" class="text-center">Actions</th>
                              </tr>
                        </thead>
                        <tbody>
                              <% @shopping_cart.cart_items.each do |cart_item|%>
                                 <tr>
                                    <% item = cart_item.item%>
                                    <td class="text-center">
                                       <a href="<%= show_path({:pc=> item.class , :pi=> item.id })%>">
                                          <img src="<%= item.image_url%>" width="50px" height="50px"/> 
                                       </a>
                                    </td>
                                    <td class="text-center"><%= item.name%></td>
                                    <td class="text-center"><%= cart_item.quantity%></td>
                                    <td class="text-center">₹ <%= cart_item.price * cart_item.quantity  %></td>
                                    <td class="text-center">
                                       <button class="btn btn-sm btn-danger remove-from-cart" data-product-qty="<%= cart_item.quantity%>" data-product-id="<%= item.id%>" data-product-class="<%= item.class.to_s%>" ><i class="fa fa-trash"></i> </button> 
                                    </td>
                                 </tr>
                              <% end %>
                              <tr>
                                 <td></td>
                                 <td></td>
                                 <td></td>
                                 <td>Sub-Total</td>
                                 <td class="text-right">₹ <%= @shopping_cart.subtotal%></td>
                              </tr>
                              <tr>
                                 <td></td>
                                 <td></td>
                                 <td></td>
                                 <td>Shipping</td>
                                 <td class="text-right">₹ <%= @shopping_cart.shipping_cost%></td>
                              </tr>
                              <tr>
                                 <td></td>
                                 <td></td>
                                 <td></td>
                                 <td><strong>Total</strong></td>
                                 <td class="text-right"><strong>₹ <%= @shopping_cart.subtotal%></strong></td>
                              </tr>
                        </tbody>
                     </table>
                  </div>
            </div>
            <div class="col mb-2">
                  <div class="row">
                     <div class="col-sm-12  col-md-6">
                        <a class="btn  btn-primary btn-light text-uppercase"  href="<%= root_path %>">Continue Shopping</a>
                     </div>
                     <div class="col-sm-12 col-md-6 text-right">
                        <button class="btn  btn-success text-uppercase checkout-btn" >Checkout</button>
                     </div>
                  </div>
            </div>
         </div>
      <% else %>
         <div class="row white-box ">
            <div class="col-sm-12 text-center"> 
               <h3>Shopping cart is empty please add items first</h3>
            </div>
            <br/>
            <br/>
            <br/>
            <div class="col-sm-12 text-center">
               <a class="btn  btn-primary btn-light text-uppercase"  href="<%= root_path %>">Continue Shopping</a>
            </div>
         </div>
      <% end %>
      
   </div>
</div>

<script> 
$(function(){
   $(".checkout-btn").unbind('click').bind('click', function(){
      alert("Order has been successfully placed")
      window.location.href="<%= root_path %>"
   })
    $(".remove-from-cart").unbind('click').bind('click',  function(){
            let $closestTr = $(this).closest('tr');
            let data ={
                pc: $(this).attr('data-product-class'),
                pi: $(this).attr('data-product-id'),
                qt: $(this).attr('data-product-qty')
            }
            $.ajax({url: "<%=remove_from_cart_path%>",
                data: JSON.stringify(data), 
                type: "POST",
                dataType: 'json',
                contentType : 'application/json',
                success: function(res){
                  alert(res.message);
                  $closestTr.remove()
            }});
        })
})
</script>

app/views/home/index.html.erb
<%selected_product = params[:p] %>
<%selected_guitar_type = params[:t] %>
<% selected_brands = params[:b].split(",") %>
<% selected_strings = params[:n].split(",") %>
<div class="row">
    <div class="col-md-3 margin-top-20">
        <div class="panel panel-default">
            <div class="panel-heading">Items</div>
            <div class="panel-body">
                <div class="row">
                   <div class="col-sm-12">
                        <% $PRODUCTS.each do |product|%>
                            <div class="form-check">
                                <label class="custom-control custom-radio">
                                    <% if selected_product == product[1] %> 
                                        <input id="radio1" name="product" type="radio" class="custom-control-input"  value="<%= product[1]%>" checked="" data-value="<%= product[1]%>" data-change="product">
                                    <% else %>
                                        <input id="radio11" name="product" type="radio" class="custom-control-input"  value="<%= product[1]%>" data-value="<%= product[1]%>" data-change="product">
                                    <% end %>
                                    <span class="custom-control-indicator"></span>
                                    <span class="custom-control-description"><%= product[0] %> </span>
                                </label>
                            </div>
                        <% end%>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">Types</div>
            <div class="panel-body">
                <div class="row">
                   <div class="col-sm-12">
                        <% $GUITAR_TYPES.each do |guitar|%>
                            <div class="form-check">
                                <label class="custom-control custom-radio">
                                    <% if selected_guitar_type == guitar[1] %> 
                                        <input id="radio2" name="guitar_type" type="radio" class="custom-control-input" value="<%= guitar[1]%>" checked="" data-value="<%= guitar[1]%>" data-change="guitar_type">
                                    <% else %>
                                        <input id="radio22" name="guitar_type" type="radio" class="custom-control-input" value="<%= guitar[1]%>" data-value="<%= guitar[1]%>" data-change="guitar_type">
                                    <% end %>
                                    <span class="custom-control-indicator"></span>
                                    <span class="custom-control-description"><%= guitar[0] %> </span>
                                </label>
                            </div>
                        <% end%>
                    </div>
                </div>
            </div>
        </div>
        <% if @brands.present? %>
            <div class="panel panel-default">
                <div class="panel-heading">Brands</div>
                <div class="panel-body">
                    <div class="row">
                    <div class="col-sm-12">
                            <% @brands.each do |brand|%>
                                <div class="form-check">
                                    <label class="custom-control custom-checkbox">
                                        <% if selected_brands.include?(brand) %> 
                                            <input type="checkbox" name='brand'  value="<%= brand%>" class="custom-control-input" checked="">
                                        <% else %>
                                            <input type="checkbox" name='brand' value="<%= brand%>" class="custom-control-input">
                                        <% end %>
                                        <span class="custom-control-indicator"></span>
                                        <span class="custom-control-description"><%= brand%></span>
                                    </label>
                                </div>
                            <% end%>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
        <% if @no_of_strings.present? %>
            <div class="panel panel-default">
                <div class="panel-heading">Number of Strings</div>
                <div class="panel-body">
                    <div class="row">
                    <div class="col-sm-12">
                            <% @no_of_strings.each do |nos|%>
                                <div class="form-check">
                                    <label class="custom-control custom-checkbox">
                                        <% if selected_strings.include?(nos.to_s) %> 
                                            <input type="checkbox" name='nos'  value="<%= nos%>" class="custom-control-input" checked="">
                                        <% else %>
                                            <input type="checkbox" name='nos' value="<%= nos%>" class="custom-control-input">
                                        <% end %>
                                        <span class="custom-control-indicator"></span>
                                        <span class="custom-control-description"><%= nos %></span>
                                    </label>
                                </div>
                            <% end%>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
        <div class="panel panel-default hide">
            <div class="panel-heading">Price</div>
            <div class="panel-body">
                <div class="col-md-12">
                    <div id="range_03"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8 margin-top-20">
        <div class="white-box">
            <div class="row">
                <% if @products.present? %>
                    <% @products.each do |product| %>
                        <div class="col-md-4" >
                           <%= render :partial=>'card', :locals=>{:product=> product}%>
                        </div>

                    <% end %>
                <% else %>
                    
                    <div class="col-md-12  margin-top-3">
                        <div class="card text-center">
                            <div class="card-body">
                                <h4 class="card-title">No Item available</h4>
                                <p class="card-text">oops ! No items are available for selected category</p>
                            </div>
                        </div>
                    </div>
                   
                <% end %>
            </div>
        </div>
    </div>
</div>

<script>
    $(function() {
        $("#range_03").ionRangeSlider({
            type: "double",
            grid: true,
            min: 0,
            max: 10000,
            from: 200,
            to: 2000,
            prefix: "₹",
            onFinish: function (data) {
                // applyFilter();
            }
        });
        $(".add-to-cart").unbind('click').bind('click',  function(){
            let data ={
                pc: $(this).attr('data-product-class'),
                pi: $(this).attr('data-product-id')
            }
            $.ajax({url: "<%=add_to_cart_path%>",
                data: JSON.stringify(data), 
                type: "POST",
                dataType: 'json',
                contentType : 'application/json',
                success: function(res){
                alert('item has been added to cart')
                    
            }});
        })

        $(".custom-control-input").unbind('change').bind('change', function(){
            applyFilter();
        });

    })
    function applyFilter(){
        var selected_brands =[], selected_strings=[];
        $.each($(".custom-control-input[name='brand']:checked"), function(){            
            selected_brands.push($(this).val());
        });
        $.each($(".custom-control-input[name='nos']:checked"), function(){            
            selected_strings.push($(this).val());
        });
        
        let url ="/?p="+$('.custom-control-input[name="product"]:checked').val() +'&t='+$('.custom-control-input[name="guitar_type"]:checked').val()+"&b="+selected_brands.join(',')+"&n="+selected_strings.join(',');

        window.location.href =url
    }
</script>

app/views/home/show.html.erb
<div class="row margin-top-20">
    <div class="col-sm-8 offset-sm-2">
        <div class="row white-box">
            <div class="col-sm-12 ">
                <div class="row product-bg">
                    <div class="col-lg-4 col-md-4 col-xs-12 sticky">
                        <ul class="thumbnails">
                            <li>
                                <a class="thumbnail" href="<%= @product.image_url%>" >
                                <div style="max-height: 300px;" class="zoomWrapper"><img data-zoom-image="<%= @product.image_url%>" src="<%= @product.image_url%>" id="zoom_03" class="img-responsive center-block" alt="image" style="position: absolute;"></div>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-8 col-lg-8  col-xs-12 pro-content">
                        <h1><%= @product.name%></h1>
                        <h3 class="text-muted"><%= @product.description.truncate(150, separator: ' ') %></h3>
                        <hr class="producthr">
                        <ul class="list-unstyled">
                            <li><span class="text-decor">Brand:</span><%= @product.brand.name%></li>
                            <li><span class="text-decor">Product Code:</span> <%= @product.serial_number.to_s%></li>
                            <% if @product.class.to_s == "Guitar"%>
                                <li><span class="text-decor">Number of strings:</span> <%= @product.number_of_strings.to_s%></li>
                            <% end %>
                            <hr class="producthr">
                        </ul>
                        <ul class="list-unstyled">
                            <ul class="list-inline">
                                <li class="text-decor-bold proprice">
                                <h2>₹ <%= @product.price%></h2>
                                </li>
                                
                            </ul>
                        </ul>
                        <div id="product">
                            <hr class="producthr">
                            <div class="form-group">
                                <ul class="list-inline">
                                <li class="op-box qtlabel">
                                    <label class="control-label text-decorop" for="input-quantity">Qty</label>
                                </li>
                                <li class="op-box qty-plus-minus">
                                    <button type="button" class="form-control pull-left btn-number btnminus"  data-type="minus" data-field="quantity">
                                    <span class="glyphicon glyphicon-minus"></span>
                                    </button>
                                    <input id="input-quantity" type="text" name="quantity" value="1" size="2" class="form-control input-number pull-left">
                                    <input type="hidden" name="product_id" value="30">
                                    <button type="button" class="form-control pull-left btn-number btnplus" data-type="plus" data-field="quantity">
                                    <span class="glyphicon glyphicon-plus"></span>
                                    </button>
                                    <button type="button" data-product-class="<%= @product.class%>" data-product-id="<%= @product.id%>" id="button-cart" data-loading-text="Loading..." class="btn add-to-cart btn-primary margin-left-10 add-to-cart">Add to Cart</button>
                                </li>
                                </ul>
                                
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
            <div class="col-sm-12 ">
                <hr/>
            </div>
            <div class="col-sm-12 ">
                <h2 class="text-center">People who bought this, also bought this<h2>
                <div class="carousel">
                    <% @related_products.each do |related_product|%>
                        <div class="related-product-card">
                            <a href="<%= show_path({:pc=> related_product.class , :pi=> related_product.id })%>">
                                <img src="<%= related_product.image_url%>" height="200" width= "100"/>
                            </a>
                            <div class="thumb-content text-center">
                                <h4><%= (related_product.name.present?) ? related_product.name  : 'NA' %></h4>
                                <p class="item-price"><h5><span class="text-muted">$250.00</span></h5></p>
                            </div>	

                        </div>
                    <% end %>
                    
                </div>
            </div>
            
        </div>
    </div>
</div>



<script>
$(function(){
    // $('.slick-wrapper').slick({
    //     slidesToShow: 4,
    //     slidesToScroll: 1,
    //     centerPadding: '60px',
    //     arrows: true,
    // });
    $('.carousel').slick({
        slidesToShow: 3,
        slidesToScroll: 1,
        dots:true,
        centerMode: true,
    });
    $('.btnminus').unbind('click').bind('click', function(){
        updateCount('sub');
    });
    $('.btnplus').unbind('click').bind('click', function(){
        updateCount('add');
    })

    $(".add-to-cart").unbind('click').bind('click',  function(){
            let data ={
                pc: $(this).attr('data-product-class'),
                pi: $(this).attr('data-product-id'),
                qt:  $("#input-quantity").val()
            }
            $.ajax({url: "<%=add_to_cart_path%>",
                data: JSON.stringify(data), 
                type: "POST",
                dataType: 'json',
                contentType : 'application/json',
                success: function(res){
                    alert(res.message)
                },
                error: function(res){
                    alert(res.responseJSON.message)
                }
                });
        })
    function updateCount(action){
        let existingCount = parseInt($("#input-quantity").val());
        existingCount = (action == 'add') ? (existingCount + 1) : (existingCount - 1)

        if(existingCount > 0){
            $("#input-quantity").val(existingCount)
        }
    }
})
</script>